---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Builds the route tables and a small set of basic routes which will be added to as the cloud solution takes shape.
  * Route Tables
  * Route Table Associations with pre-existing subnets
  * Public Route to Internet Gateway

Parameters:
  VpcId:
    Description: ID of the VPC
    Type: AWS::EC2::VPC::Id
  EnvName:
    Description: Name of the environment and will be used for tagging resources
    Type: String
  ZonesRequired:
    Description: Number of Zones required
    Default: 1
    MinValue: 1
    MaxValue: 4
    Type: Number
  NetworkLayers:
    Description: Number of layers to be used.
    MaxValue: 3
    MinValue: 1
    Default: 2
    ConstraintDescription: Must be a number between 1 and 3 inclusive.
    Type: Number
  VpcType:
    Description: Determine a public or private VPC
    AllowedValues: 
      - public
      - private
    ConstraintDescription: Must be either public or private.
    Default: public
    Type: String  

Mappings: 
  VpcStructure: 
    private: 
      "1": ["private"]
      "2": ["private","persistence"]
      "3": ["private","public","persistence"]
    public: 
      "1": ["public"]
      "2": ["private","public"]
      "3": ["private","public","persistence"]

Conditions:
  TwoLayerResource: 
    !Or
    - !Equals [ !Ref NetworkLayers, 2 ]
    - !Equals [ !Ref NetworkLayers, 3 ]
  ThreeLayerResource: 
    !Equals [ !Ref NetworkLayers, 3 ]

Resources:
# Public route table with associations
  RouteTable1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: route.yaml
      TimeoutInMinutes: 5
      Parameters:
        VpcId:            !Ref VpcId
        EnvName:          !Ref EnvName
        EnvType:          !Select 
        - 0
        - Fn::FindInMap: [VpcStructure, !Ref VpcType, !Ref NetworkLayers]
        ZonesRequired:    !Ref ZonesRequired

# Private route tables with associations
  RouteTable2:
    Type: AWS::CloudFormation::Stack
    Condition: TwoLayerResource
    Properties:
      TemplateURL: route.yaml
      TimeoutInMinutes: 5
      Parameters:
        VpcId:            !Ref VpcId
        EnvName:          !Ref EnvName
        EnvType:          !Select 
        - 1
        - Fn::FindInMap: [VpcStructure, !Ref VpcType, !Ref NetworkLayers]
        ZonesRequired:    !Ref ZonesRequired

# Persistence route tables with associations
  RouteTable3:
    Type: AWS::CloudFormation::Stack
    Condition: ThreeLayerResource
    Properties:
      TemplateURL: route.yaml
      TimeoutInMinutes: 5
      Parameters:
        VpcId:            !Ref VpcId
        EnvName:          !Ref EnvName
        EnvType:          !Select 
        - 2
        - Fn::FindInMap: [VpcStructure, !Ref VpcType, !Ref NetworkLayers]
        ZonesRequired:    !Ref ZonesRequired
