---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Builds the route tables and a small set of basic routes which will be added to as the cloud solution takes shape.
  * Route Tables
  * Route Table Associations with pre-existing subnets

Parameters:
  VpcId:
    Description: ID of the VPC
    Type: AWS::EC2::VPC::Id
  EnvName:
    Description: Name of the environment and will be used for tagging resources
    Type: String
  ZonesRequired:
    Description: Number of Zones required
    Default: 1
    MinValue: 1
    MaxValue: 4
    Type: Number
  EnvType:
    Description: Type of env, used to find the associated subnets
    AllowedValues: 
      - public
      - private
      - persistence
    ConstraintDescription: Must be either public, private or persistence.
    Default: public
    Type: String  

Conditions:
  PublicEnvType:
    !Equals [ !Ref EnvType, public ]
  NonPublicTwoZoneResource: !And
    - !Not [ !Equals [ !Ref EnvType, public ] ]
    - !Or 
      - !Equals [ !Ref ZonesRequired, 2 ]
      - !Equals [ !Ref ZonesRequired, 3 ]
      - !Equals [ !Ref ZonesRequired, 4 ]

  NonPublicThreeZoneResource: !And
    - !Not [ !Equals [ !Ref EnvType, public ] ]
    - !Or 
      - !Equals [ !Ref ZonesRequired, 2 ]
      - !Equals [ !Ref ZonesRequired, 3 ]

  NonPublicFourZoneResource: !And
    - !Not [ !Equals [ !Ref EnvType, public ] ]
    - !Equals [ !Ref ZonesRequired, 4 ]

Resources:
  RouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Sub ${EnvName}:rt-${EnvType}-a
  AttachSubnetA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvName}:sn-${EnvType}-a:id"
      RouteTableId: !Ref RouteTableA

  RouteTableB:
    Type: AWS::EC2::RouteTable
    Condition: NonPublicTwoZoneResource
    Properties:
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Sub ${EnvName}:rt-${EnvType}-b
  AttachSubnetB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: NonPublicTwoZoneResource
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvName}:sn-${EnvType}-b:id"
      RouteTableId: !If [NonPublicTwoZoneResource, !Ref RouteTableB, !Ref RouteTableA ]
  
  RouteTableC:
    Type: AWS::EC2::RouteTable
    Condition: NonPublicThreeZoneResource
    Properties:
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Sub ${EnvName}:rt-${EnvType}-c
  AttachSubnetC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: NonPublicThreeZoneResource
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvName}:sn-${EnvType}-c:id"
      RouteTableId: !If [NonPublicThreeZoneResource, !Ref RouteTableC, !Ref RouteTableA ]

  RouteTableD:
    Type: AWS::EC2::RouteTable
    Condition: NonPublicFourZoneResource
    Properties:
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Sub ${EnvName}:rt-${EnvType}-d
  AttachSubnetD:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: NonPublicFourZoneResource
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvName}:sn-${EnvType}-d:id"
      RouteTableId: !If [NonPublicFourZoneResource, !Ref RouteTableD, !Ref RouteTableA ]

  # Define a standard route for the public route table
  InternetAccess:
    Type: AWS::EC2::Route
    Condition: PublicEnvType
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref RouteTableA
      GatewayId:
        Fn::ImportValue:
          !Sub "${EnvName}:igw:id"

Outputs:
  RouteTableA:
    Value: !Ref RouteTableA
    Description: A reference to the RouteTableA
    Export:
      Name: !Sub ${EnvName}:rt-${EnvType}-a:id 
  RouteTableB:
    Condition: NonPublicTwoZoneResource
    Value: !Ref RouteTableB
    Description: A reference to the RouteTableB
    Export:
      Name: !Sub ${EnvName}:rt-${EnvType}-b:id
  RouteTableC:
    Condition: NonPublicThreeZoneResource
    Value: !Ref RouteTableC
    Description: A reference to the RouteTableC
    Export:
      Name: !Sub ${EnvName}:rt-${EnvType}-c:id 
  RouteTableD:
    Condition: NonPublicFourZoneResource
    Value: !Ref RouteTableD
    Description: A reference to the RouteTableD
    Export:
      Name: !Sub ${EnvName}:rt-${EnvType}-d:id 
