---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CidrCalculator Lambda Function for use as a CFN custom resources.
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SubnetCidrCalculator
      Description: Function calculates the Cidr Ranges, for use with CFN
      CodeUri: ../dist/calculator.zip
      Handler: calculator.handler
      Runtime: python3.6
